## Imports

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Get data into a pandas dataframe

In [7]:
biographical = pd.read_excel("01 scorecard_dataset.xlsx")
biographical.head()

      ID  Gender Education  Offences
0  10005    Male  Grade 12         4
1  10026    Male  Grade 12         0
2  10031    Male    Degree         0
3  10034  Female  Grade 12         0
4  10057    Male  Grade 12         2

In [13]:
credit_df = pd.read_excel("01 scorecard_dataset.xlsx", sheet_name=1)
for i in range(2,10):
    credit_df = pd.concat([credit_df, pd.read_excel("01 scorecard_dataset.xlsx", sheet_name=i)], ignore_index=True)

credit_df.head()

,ID,IntRate,Income,DTI,LoanAmt,HistLen,Utilisation,Age,EmpStatus,HomeOwn,Purpose,default
0,10005.0,17.75,180437.0,1.75,537093.0,7.02,35.28,32.4,Salaried,Mortgage,Vehicle,1.0
1,10026.0,33.75,7701.0,0.51,25785.0,24.24,82.92,50.8,Unemployed,Rent,Vehicle,0.0
2,10031.0,18.75,331021.0,1.72,974609.0,23.00,76.17,54.0,Salaried,Rent,Vehicle,0.0
3,10034.0,18.75,1141777.0,1.27,3939620.0,28.03,91.63,52.8,Self-employed,Mortgage,Home_improvement,0.0
4,10057.0,35.00,2188.0,0.52,4568.0,4.46,22.91,31.2,Unemployed,Rent,Debt_consolidation,0.0

## Save as .csv files

In [14]:
biographical.to_csv("Biographical_raw.csv", index=False)
credit_df.to_csv("Credit_data_raw.csv", index=False)